name: Release

on:
  workflow_dispatch:
    inputs:
      version: 
        description: '版本号'
        required: true
        default: '0.0.0'

      
jobs:
  release:
    runs-on: windows-latest

    env:
      Project_Directory: DanmakuFrostMaster
      Project_File_Name: DanmakuFrostMaster.csproj
      Nuget_File_Name: DanmakuFrostMaster.nuspec
      GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN  }}
      nuget_push_key: ${{ secrets.NUGET_PUSH_KEY }}

    steps:
    
    - name: Configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 32GB
        maximum-size: 32GB
        disk-root: "C:"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: release-drafter/release-drafter@v5
      name: Create release draft
      id: release-drafter

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet.exe for use with actions          
      uses: NuGet/setup-nuget@v1.2.0
        
                  
    - name: Windows SDK Install
      uses: ChristopheLav/windows-sdk-install@v1.0.1
      with:
        version-sdk: 18362
        features: 'OptionId.WindowsPerformanceToolkit,OptionId.WindowsDesktopDebuggers,OptionId.AvrfExternal,OptionId.NetFxSoftwareDevelopmentKit,OptionId.WindowsSoftwareLogoToolkit,OptionId.IpOverUsb,OptionId.MSIInstallTools,OptionId.SigningTools,OptionId.UWPManaged,OptionId.UWPCPP,OptionId.UWPLocalized,OptionId.DesktopCPPx86,OptionId.DesktopCPPx64,OptionId.DesktopCPParm,OptionId.DesktopCPParm64'

    - name: Build
      run: msbuild .\$env:Project_Directory\$env:Project_File_Name /restore
      
    - name: Create nupkg
      run: nuget pack .\$env:Project_Directory\$env:Nuget_File_Name

    - name: Push NugetServer
      run: dotnet nuget push -s http://nuget.muyan233.top:681/v3/index.json -k $env:nuget_push_key .\DanmakuFrostMaster.muyan.${{github.event.inputs.version}}.nupkg

    - name: Update release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN  }}
      with:
        upload_url: ${{ steps.release-drafter.outputs.upload_url }}
        asset_path: .\DanmakuFrostMaster.muyan.${{github.event.inputs.version}}.nupkg
        asset_name: DanmakuFrostMaster.muyan.${{github.event.inputs.version}}.nupkg
        asset_content_type: application/zip